default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: shop_app_db # hardy_prod_11_may_2022 # hardy_nutritionals
  username: sandeepsingh
  # password: 123456

test:
  <<: *default
  host: localhost
  database: shop_app_db
  username: sandeepsingh
  # password: 123456

production:
  <<: *default
  database: shop_app_db
  username: sandeepsingh
  # password: 123456
